headless: true
record_video: false
interval_seconds: 120

database:
  url: postgresql+asyncpg://watcha:sVp3rs3cr37@immosive.h5c.lan:5433/watchawatch
  echo: false

clusters:
  patterns:
    - "\\b\\d{6}\\b"

telegram:
  enabled: true
  bot_token: "8380067264:AAHnD84mac4ONhaoht3LT8CQeV_Ii90WUrU"
  chat_id: "1651593444"         # oder "@dein_channel"
  disable_web_page_preview: true

searches:
  - name: "BlueBrixx 104966 (Large Voyager)"
    terms: 
      - "BlueBrixx"
      - "104966"
    providers:
#      - "ebay"
      - "kleinanzeigen"
  - name: "BlueBrixx 104184 (Large Enterprise-D)"
    terms: 
      - "BlueBrixx"
      - "104184"
    providers:
#      - "ebay"
      - "kleinanzeigen"
